### PR TITLE
Refactoring docker setup

### LINKED ISSUE #1: Refactor docker setup
Laradock seems heavyweight for what this app requires. It takes too long to initially install, has a massive configuration file, and creates a bunch of unused docker volumes. Also, using submodules is annoying and unnecessary.

Let's refactor the docker setup to a single docker-compose.yml that has a workspace for development and a mongodb service and whatever the minimal requirements for running the app are.

### PR DESCRIPTION
**Pull request by mrcnc**
To resolve #1

### CODE REVIEW

**Comment by mrcnc** [comment]
There's still a bug when viewing organizations, but this is enough to remove laradock and run the app successfully a more efficient docker setup.

**Comment by nihonjinrxs** [comment]
During the dependency install step (`docker-compose run --rm app composer install`), I noticed a number of deprecations and an abandoned package. We'll need to handle those eventually, but I understand putting those off for now.

More importantly, also during that step, I got an invalid characters exception which failed the process at the post-install:
```
Compiling common classes

                                                                               
  [ErrorException]                                                             
  Invalid characters passed for attempted conversion, these have been ignored  
                                                                               

Script php artisan optimize handling the post-install-cmd event returned with error code 1
```

The mongo startup (`docker-compose up mongo`) also resulted in a failure:

```
mongo_1  | 2020-08-14T03:58:41.101+0000 F CONTROL  [main] Failed global initialization: FileNotOpen: Failed to open "/var/log/mongodb/mongod.log"
app_mongo_1 exited with code 1
```
With that failure, I'm unable to move forward with the install without spending a bit of time debugging. I'll try to do some of that this weekend. Stopping for the night now though.

**Comment by mrcnc** [comment]
I was able to simulate the error on a linux machine....so I'm investigating why it might not be happening on my laptop
```
Starting app_mongo_1 ... done
Attaching to app_mongo_1
mongo_1  | 2020-09-06T21:53:52.389+0000 F CONTROL  [main] Failed global initialization: FileNotOpen: Failed to open "/var/log/mongodb/mongod.log"
```

**Comment by mrcnc** [comment]
Got it to work on the server after some tweaking

**Review by nihonjinrxs — APPROVED** [review]

**Pull request merged**
